title       = "nlab"
baseURL     = "https://nlab-cli.tamnd.com/"
description = "Browse the nLab mathematics wiki"
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/nlab-cli"
